/*******************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.9.
 *
 * You need to add your implementation here to:
 *    - get telemetry data from device/sensor
 *    - set read-only property data
 *    - handle read-write property callback
 *    - process device command
 *
 * Generated Date: 2020/06/07
 *******************************************************************************************/

#include "EnOceanPnPTest2_1yu_impl.h"
#include "utilities/digitaltwin_serializer.h"
#include "utilities/deviceinformation_5kj_interface.h"
#include "utilities/enoceanpnptest2_sensor_interface.h"

#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <sys/time.h>

#define Payload_Buffer_Size 256

static int lrand_start = 0;

void lrand_init()
{
        unsigned int seed;
        struct timeval tv;

	if (lrand_start == 0) {
	  lrand_start = 1;
	  gettimeofday(&tv, NULL);
	  seed = (unsigned int) tv.tv_usec;
	  //printf("seed=%u, RAND_MAX=%d\n", seed, RAND_MAX);
	  srand(seed);
	}
}

double lrand(double min, double max)
{
        int r;
        double d, rate;

	lrand_init();
        d = (double) rand();
        rate = d / RAND_MAX; /* rate=0~1.0 */
        return(min + (max - min) * rate);
}

void SendTelemetry_Succeeded_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on success.

    LogInfo("DigitalTwin successfully delivered telemetry message for component %s", interfaceName);
}

void SendTelemetry_Error_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on failure.

    LogInfo("DigitalTwin failed to deliver telemetry message for %s", interfaceName);
}

void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback reporting property on success.

    LogInfo("DigitalTwin successfully report writable property for %s::%s", interfaceName, propertyName);
}

void ReportProperty_Error_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback of reporting property on failure.

    LogInfo("DigitalTwin failed to report writable property for %s::%s", interfaceName, propertyName);
}

char* DeviceInformation_5kj_Property_GetManufacturer()
{
    // TODO: provide implementation here
    return "Device Drivers";
}

char* DeviceInformation_5kj_Property_GetModel()
{
    // TODO: provide implementation here
    return "EnOcean Gateway";
}

char* DeviceInformation_5kj_Property_GetSwVersion()
{
    // TODO: provide implementation here
    return "0.1";
}

char* DeviceInformation_5kj_Property_GetOsName()
{
    // TODO: provide implementation here
    return "Raspbian GNU/Linux 9";
}

char* DeviceInformation_5kj_Property_GetProcessorArchitecture()
{
    // TODO: provide implementation here
    return "armv7l";
}

char* DeviceInformation_5kj_Property_GetProcessorManufacturer()
{
    // TODO: provide implementation here
    return "raspberry pi";
}

long DeviceInformation_5kj_Property_GetTotalStorage()
{
    // TODO: provide implementation here
    return 16384L;
}

long DeviceInformation_5kj_Property_GetTotalMemory()
{
    // TODO: provide implementation here
    return 1024L;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadTemperature()
{
    double value = lrand(15, 33);
    // TODO: provide implementation here
    return value;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadHumidity()
{
    double value = lrand(30, 90);
    // TODO: provide implementation here
    return value;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadIllumination()
{
    double value = lrand(0, 100000);
    // TODO: provide implementation here
    return value;
}

ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationstatus()
{
	int value = (int) lrand(0, 2);
    // TODO: provide implementation here
    //return ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS_periodicupdate;
    return value;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationx()
{
    double value = lrand(-2.5, 2.5);
    // TODO: provide implementation here
    return value;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationy()
{
    double value = lrand(-2.5, 2.5);
    // TODO: provide implementation here
    return value;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationz()
{
    double value = lrand(-2.5, 2.5);
    // TODO: provide implementation here
    return value;
}

ENOCEANPNPTEST2_SENSOR_CONTACT EnOceanPnPTest2_sensor_Telemetry_ReadContact()
{
    int value = (int) lrand(0, 1);
    // TODO: provide implementation here
    //return ENOCEANPNPTEST2_SENSOR_CONTACT_UNDEFINED;
    //return ENOCEANPNPTEST2_SENSOR_CONTACT_open;
    return value;
}
