/*******************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.9.
 *
 * You need to add your implementation here to:
 *    - get telemetry data from device/sensor
 *    - set read-only property data
 *    - handle read-write property callback
 *    - process device command
 *
 * Generated Date: 2020/06/07
 *******************************************************************************************/

#include "EnOceanPnPTest2_1yu_impl.h"
#include "utilities/digitaltwin_serializer.h"
#include "utilities/deviceinformation_5kj_interface.h"
#include "utilities/enoceanpnptest2_sensor_interface.h"

#define Payload_Buffer_Size 256

void SendTelemetry_Succeeded_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on success.

    LogInfo("DigitalTwin successfully delivered telemetry message for component %s", interfaceName);
}

void SendTelemetry_Error_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on failure.

    LogInfo("DigitalTwin failed to deliver telemetry message for %s", interfaceName);
}

void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback reporting property on success.

    LogInfo("DigitalTwin successfully report writable property for %s::%s", interfaceName, propertyName);
}

void ReportProperty_Error_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback of reporting property on failure.

    LogInfo("DigitalTwin failed to report writable property for %s::%s", interfaceName, propertyName);
}

char* DeviceInformation_5kj_Property_GetManufacturer()
{
    // TODO: provide implementation here
    return "abc";
}

char* DeviceInformation_5kj_Property_GetModel()
{
    // TODO: provide implementation here
    return "abc";
}

char* DeviceInformation_5kj_Property_GetSwVersion()
{
    // TODO: provide implementation here
    return "abc";
}

char* DeviceInformation_5kj_Property_GetOsName()
{
    // TODO: provide implementation here
    return "abc";
}

char* DeviceInformation_5kj_Property_GetProcessorArchitecture()
{
    // TODO: provide implementation here
    return "abc";
}

char* DeviceInformation_5kj_Property_GetProcessorManufacturer()
{
    // TODO: provide implementation here
    return "abc";
}

long DeviceInformation_5kj_Property_GetTotalStorage()
{
    // TODO: provide implementation here
    return 0L;
}

long DeviceInformation_5kj_Property_GetTotalMemory()
{
    // TODO: provide implementation here
    return 0L;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadTemperature()
{
    // TODO: provide implementation here
    return 0.0;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadHumidity()
{
    // TODO: provide implementation here
    return 0.0;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadIllumination()
{
    // TODO: provide implementation here
    return 0.0;
}

ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationstatus()
{
    // TODO: provide implementation here
    return ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS_UNDEFINED;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationx()
{
    // TODO: provide implementation here
    return 0.0;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationy()
{
    // TODO: provide implementation here
    return 0.0;
}

double EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationz()
{
    // TODO: provide implementation here
    return 0.0;
}

ENOCEANPNPTEST2_SENSOR_CONTACT EnOceanPnPTest2_sensor_Telemetry_ReadContact()
{
    // TODO: provide implementation here
    return ENOCEANPNPTEST2_SENSOR_CONTACT_UNDEFINED;
}

