/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.9.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 2020/06/07
 ***********************************************************************************************/

#ifndef DIGITALTWIN_SERIALIZER
#define DIGITALTWIN_SERIALIZER

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "azure_c_shared_utility/xlogging.h"
#include "parson.h"

#include "../EnOceanPnPTest2_1yu_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

bool DeviceInformation_5kj_SerializeManufacturerProperty(char * payloadBuffer, int size);

bool DeviceInformation_5kj_SerializeModelProperty(char * payloadBuffer, int size);

bool DeviceInformation_5kj_SerializeSwVersionProperty(char * payloadBuffer, int size);

bool DeviceInformation_5kj_SerializeOsNameProperty(char * payloadBuffer, int size);

bool DeviceInformation_5kj_SerializeProcessorArchitectureProperty(char * payloadBuffer, int size);

bool DeviceInformation_5kj_SerializeProcessorManufacturerProperty(char * payloadBuffer, int size);

bool DeviceInformation_5kj_SerializeTotalStorageProperty(char * payloadBuffer, int size);

bool DeviceInformation_5kj_SerializeTotalMemoryProperty(char * payloadBuffer, int size);

bool EnOceanPnPTest2_sensor_SerializeTemperatureTelemetry(char * payloadBuffer, int size);

bool EnOceanPnPTest2_sensor_SerializeHumidityTelemetry(char * payloadBuffer, int size);

bool EnOceanPnPTest2_sensor_SerializeIlluminationTelemetry(char * payloadBuffer, int size);

bool EnOceanPnPTest2_sensor_SerializeAccelerationstatusTelemetry(char * payloadBuffer, int size);

bool EnOceanPnPTest2_sensor_SerializeAccelerationxTelemetry(char * payloadBuffer, int size);

bool EnOceanPnPTest2_sensor_SerializeAccelerationyTelemetry(char * payloadBuffer, int size);

bool EnOceanPnPTest2_sensor_SerializeAccelerationzTelemetry(char * payloadBuffer, int size);

bool EnOceanPnPTest2_sensor_SerializeContactTelemetry(char * payloadBuffer, int size);

#ifdef __cplusplus
}
#endif

#endif // DIGITALTWIN_SERIALIZER
