/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.9.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 2020/06/08
 ***********************************************************************************************/

#include "digitaltwin_serializer.h"

//
// Serialize telemetry data
//

bool EnOceanPnPTest2_sensor_SerializeTemperatureTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double temperature = EnOceanPnPTest2_sensor_Telemetry_ReadTemperature();

    int neededSize = snprintf(NULL, 0, "%f", temperature);

    if (neededSize > size - 1)
    {
        LogError("Failed to build temperature payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", temperature);
    }

    return true;
}

bool EnOceanPnPTest2_sensor_SerializeHumidityTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double humidity = EnOceanPnPTest2_sensor_Telemetry_ReadHumidity();

    int neededSize = snprintf(NULL, 0, "%f", humidity);

    if (neededSize > size - 1)
    {
        LogError("Failed to build humidity payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", humidity);
    }

    return true;
}

bool EnOceanPnPTest2_sensor_SerializeIlluminationTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double illumination = EnOceanPnPTest2_sensor_Telemetry_ReadIllumination();

    int neededSize = snprintf(NULL, 0, "%f", illumination);

    if (neededSize > size - 1)
    {
        LogError("Failed to build illumination payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", illumination);
    }

    return true;
}

bool EnOceanPnPTest2_sensor_SerializeAccelerationstatusTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS value = EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationstatus();

    int intValue;
    switch (value)
    {
    case ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS_periodicupdate:
        intValue = 0;
        break;

    case ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS_threshold1Exceeded:
        intValue = 1;
        break;

    case ENOCEANPNPTEST2_SENSOR_ACCELERATIONSTATUS_threshold2exceeded:
        intValue = 2;
        break;

    default:
        LogError("Invalid accelerationstatus value");
        return false;
    }

    int neededSize = snprintf(NULL, 0, "%d", intValue);
    if (neededSize > size - 1)
    {
        LogError("Failed to build accelerationstatus payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%d", intValue);
    }

    return true;
}

bool EnOceanPnPTest2_sensor_SerializeAccelerationxTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double accelerationx = EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationx();

    int neededSize = snprintf(NULL, 0, "%f", accelerationx);

    if (neededSize > size - 1)
    {
        LogError("Failed to build accelerationx payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", accelerationx);
    }

    return true;
}

bool EnOceanPnPTest2_sensor_SerializeAccelerationyTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double accelerationy = EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationy();

    int neededSize = snprintf(NULL, 0, "%f", accelerationy);

    if (neededSize > size - 1)
    {
        LogError("Failed to build accelerationy payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", accelerationy);
    }

    return true;
}

bool EnOceanPnPTest2_sensor_SerializeAccelerationzTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double accelerationz = EnOceanPnPTest2_sensor_Telemetry_ReadAccelerationz();

    int neededSize = snprintf(NULL, 0, "%f", accelerationz);

    if (neededSize > size - 1)
    {
        LogError("Failed to build accelerationz payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", accelerationz);
    }

    return true;
}

bool EnOceanPnPTest2_sensor_SerializeContactTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    ENOCEANPNPTEST2_SENSOR_CONTACT value = EnOceanPnPTest2_sensor_Telemetry_ReadContact();

    int intValue;
    switch (value)
    {
    case ENOCEANPNPTEST2_SENSOR_CONTACT_open:
        intValue = 0;
        break;

    case ENOCEANPNPTEST2_SENSOR_CONTACT_close:
        intValue = 1;
        break;

    default:
        LogError("Invalid Contact value");
        return false;
    }

    int neededSize = snprintf(NULL, 0, "%d", intValue);
    if (neededSize > size - 1)
    {
        LogError("Failed to build Contact payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%d", intValue);
    }

    return true;
}

//
// Serialize read-only property
//

bool DeviceInformation_5kj_SerializeManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* manufacturer = DeviceInformation_5kj_Property_GetManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", manufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build manufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", manufacturer);
    }

    return true;
}

bool DeviceInformation_5kj_SerializeModelProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* model = DeviceInformation_5kj_Property_GetModel();

    int neededSize = snprintf(NULL, 0, "\"%s\"", model);

    if (neededSize > size - 1)
    {
        LogError("Failed to build model payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", model);
    }

    return true;
}

bool DeviceInformation_5kj_SerializeSwVersionProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* swVersion = DeviceInformation_5kj_Property_GetSwVersion();

    int neededSize = snprintf(NULL, 0, "\"%s\"", swVersion);

    if (neededSize > size - 1)
    {
        LogError("Failed to build swVersion payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", swVersion);
    }

    return true;
}

bool DeviceInformation_5kj_SerializeOsNameProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* osName = DeviceInformation_5kj_Property_GetOsName();

    int neededSize = snprintf(NULL, 0, "\"%s\"", osName);

    if (neededSize > size - 1)
    {
        LogError("Failed to build osName payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", osName);
    }

    return true;
}

bool DeviceInformation_5kj_SerializeProcessorArchitectureProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* processorArchitecture = DeviceInformation_5kj_Property_GetProcessorArchitecture();

    int neededSize = snprintf(NULL, 0, "\"%s\"", processorArchitecture);

    if (neededSize > size - 1)
    {
        LogError("Failed to build processorArchitecture payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", processorArchitecture);
    }

    return true;
}

bool DeviceInformation_5kj_SerializeProcessorManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* processorManufacturer = DeviceInformation_5kj_Property_GetProcessorManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", processorManufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build processorManufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", processorManufacturer);
    }

    return true;
}

bool DeviceInformation_5kj_SerializeTotalStorageProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long totalStorage = DeviceInformation_5kj_Property_GetTotalStorage();

    int neededSize = snprintf(NULL, 0, "%ld", totalStorage);

    if (neededSize > size - 1)
    {
        LogError("Failed to build totalStorage payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", totalStorage);
    }

    return true;
}

bool DeviceInformation_5kj_SerializeTotalMemoryProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long totalMemory = DeviceInformation_5kj_Property_GetTotalMemory();

    int neededSize = snprintf(NULL, 0, "%ld", totalMemory);

    if (neededSize > size - 1)
    {
        LogError("Failed to build totalMemory payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", totalMemory);
    }

    return true;
}

